### ISSUE TITLE
Tests for IBM device failing.

### ISSUE THREAD

**Issue by mariaschuld** [PennyLaneAI/pennylane-pq#61]
#### Issue description

The tests for the IBM device are currently failing, due to a ``user`` argument passed to IBM.

A couple of months ago, IBM deprecated their original v1 API, for a new v2 API, and it is possible that ProjectQ (which is only minimally maintained) did not update their interface accordingly.

Since this is out of the scope of this plugin, we will wait for further changes in ProjectQ.

**Comment by josh146** [comment]
It looks like ProjectQ's IBM backend was updated for the v2 API:
https://github.com/ProjectQ-Framework/ProjectQ/tree/develop/projectq/backends/_ibm

Can we modify the pinned version of ProjectQ in `requirements.txt` to the latest version, and see if this fixes the tests?

**Comment by mariaschuld** [comment]
I'm using the latest version and it fails, but this is no surprise since we are calling the IBM device using the old signature. I'll try to fix that...

**Comment by mariaschuld** [comment]
This one was long fixed.
